# Generated by Django 4.0.5 on 2022-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weatherstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=25)),
                ('service_url', models.CharField(max_length=250)),
                ('api_url', models.CharField(max_length=250)),
            ],
        ),
    ]
