# Generated by Django 4.0.5 on 2022-10-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weatherservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('wind_gusts', models.IntegerField()),
                ('temperature_day', models.IntegerField()),
                ('temperature_night', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.city')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.weatherservice')),
            ],
        ),
    ]
