# Generated by Django 4.0.5 on 2022-10-12 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='precipitation_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.weatherstatus'),
            preserve_default=False,
        ),
    ]
