# Generated by Django 4.0.5 on 2022-10-12 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_weather_precipitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='cloud',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='cloud', to='main.weatherstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precipitation_type', to='main.weatherstatus'),
        ),
    ]
