# Generated by Django 4.0.5 on 2022-10-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_weather_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='precipitation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.weatherstatus'),
        ),
    ]
